server:
  port: 2001

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 400000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximumPoolSize: 20
      minimum-idle: 5
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3307/security_demo?characterEncoding=utf-8&amp;autoReconnect=true&amp;useSSL=true
    username: root
    password: root

  redis:
    database: 10
    host: 127.0.0.1
    password: xs0529
    port: 6379



mybatis-plus:
  mapper-locations: classpath*:com/xs/example/demo/permission/user/mapper/xml/*.xml






#登录失败5分钟后再登录
loginAfterTime: 5
#登录失败次数
loginTimeLimit: 5
#保存登录时长 7天
saveLoginTime: 7
#token过期时间 1小时
tokenExpireTime: 1